[package]
name = "think_with_your_hands_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.10.4"
rand = "0.8.5"

[[bin]]
name = "seireki_wareki"
path = "src/ch1/seireki_wareki.rs"